FROM node:lts-alpine AS builder

MAINTAINER Boro

WORKDIR /app

COPY . .

RUN npm install --only-production && \
    npm cache clean --force && \
    npm run build

FROM alpine:3.20.2

RUN apk add --no-cache nginx

COPY --from=builder /app/build /usr/share/nginx/html/build

COPY /nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g","daemon off;"]
